/* ============================================================
 * main.c — Redundant Wireless Motor Controller
 * STM32F103 + FreeRTOS + nRF24 Multi-band
 * ProgressBox Internship Project 2026
 * Author: Mohamed Adem Matri
 * ============================================================ */

#include "main.h"
#include "cmsis_os.h"         // FreeRTOS
#include "nrf24_driver.h"     // nRF24L01+ driver (2.4 GHz)
#include "cc1101_driver.h"    // CC1101 driver (868/915 MHz)
#include "motor_pwm.h"        // PWM motor control
#include "redundancy.h"       // Redundancy protocol
#include "health_monitor.h"   // Health monitoring
#include <stdio.h>
#include <string.h>

/* ============================================================
 * Packet structure — sent by TX, received by RX
 * ============================================================ */
typedef struct {
    uint8_t  cmd;         // MOTOR_SPEED / MOTOR_DIR / MOTOR_STOP
    uint8_t  seq;         // sequence number 0-255
    uint32_t timestamp;   // time in milliseconds
    uint8_t  checksum;    // data integrity check
} MotorPacket_t;

/* Motor commands */
#define MOTOR_STOP   0x00
#define MOTOR_FWD    0x01
#define MOTOR_REV    0x02
#define MOTOR_SPEED  0x03

/* RF Bands */
typedef enum {
    BAND_2G4 = 0,   // nRF24L01+ @ 2.4 GHz  (primary TX-A)
    BAND_868 = 1    // CC1101    @ 868/915 MHz (backup TX-B)
} RadioBand;

/* ============================================================
 * FreeRTOS handles
 * ============================================================ */
osThreadId_t wirelessRxTaskHandle;
osThreadId_t motorCtrlTaskHandle;
osThreadId_t redundancyTaskHandle;
osThreadId_t healthMonTaskHandle;

osMessageQueueId_t motorCmdQueueHandle;   // queue: RX → Motor
osMutexId_t        activeBandMutexHandle; // mutex: protect band switch
osEventFlagsId_t   systemEventHandle;     // event: TX-A fail flag

/* Event flags */
#define EVT_TXA_FAIL     0x01
#define EVT_TXB_FAIL     0x02
#define EVT_SWITCH_DONE  0x04

/* Active band — protected by mutex */
volatile RadioBand activeBand = BAND_2G4;

/* Sequence tracker */
volatile uint8_t  lastSeqA = 0;
volatile uint8_t  lastSeqB = 0;
volatile uint32_t lastTimeA = 0;
volatile uint32_t lastTimeB = 0;

/* Timeout threshold (ms) */
#define STREAM_TIMEOUT_MS   50

/* ============================================================
 * Peripheral handles (generated by STM32CubeMX)
 * ============================================================ */
SPI_HandleTypeDef hspi1;   // SPI1 — shared by nRF24 and CC1101
TIM_HandleTypeDef htim2;   // TIM2 — PWM motor output
UART_HandleTypeDef huart1; // UART1 — debug logs

/* ============================================================
 * Function prototypes
 * ============================================================ */
void SystemClock_Config(void);
void MX_GPIO_Init(void);
void MX_SPI1_Init(void);
void MX_TIM2_Init(void);
void MX_USART1_UART_Init(void);

void Task_WirelessRX(void *argument);
void Task_MotorControl(void *argument);
void Task_Redundancy(void *argument);
void Task_HealthMonitor(void *argument);

static void log_uart(const char *msg);
static uint8_t calc_checksum(MotorPacket_t *pkt);

/* ============================================================
 * main()
 * ============================================================ */
int main(void)
{
    /* HAL init */
    HAL_Init();
    SystemClock_Config();

    /* Peripheral init */
    MX_GPIO_Init();
    MX_SPI1_Init();
    MX_TIM2_Init();
    MX_USART1_UART_Init();

    log_uart("[BOOT] System starting...\r\n");

    /* Init RF modules */
    radio_init(BAND_2G4);
    log_uart("[BOOT] nRF24L01+ initialized — BAND_2G4\r\n");

    radio_init(BAND_868);
    log_uart("[BOOT] CC1101 initialized    — BAND_868\r\n");

    /* Init motor PWM */
    motor_init(&htim2);
    log_uart("[BOOT] Motor PWM initialized\r\n");

    /* FreeRTOS kernel init */
    osKernelInitialize();

    /* Create queues, mutexes, events */
    motorCmdQueueHandle   = osMessageQueueNew(10, sizeof(MotorPacket_t), NULL);
    activeBandMutexHandle = osMutexNew(NULL);
    systemEventHandle     = osEventFlagsNew(NULL);

    /* Create tasks */
    const osThreadAttr_t rxAttr     = { .name="WirelessRX",  .priority=osPriorityHigh };
    const osThreadAttr_t motorAttr  = { .name="MotorCtrl",   .priority=osPriorityHigh };
    const osThreadAttr_t redunAttr  = { .name="Redundancy",  .priority=osPriorityNormal };
    const osThreadAttr_t healthAttr = { .name="HealthMon",   .priority=osPriorityLow };

    wirelessRxTaskHandle  = osThreadNew(Task_WirelessRX,    NULL, &rxAttr);
    motorCtrlTaskHandle   = osThreadNew(Task_MotorControl,  NULL, &motorAttr);
    redundancyTaskHandle  = osThreadNew(Task_Redundancy,    NULL, &redunAttr);
    healthMonTaskHandle   = osThreadNew(Task_HealthMonitor, NULL, &healthAttr);

    log_uart("[BOOT] FreeRTOS tasks created (4 tasks)\r\n");
    log_uart("[BOOT] TX-A active | Stream A: OK\r\n");

    /* Start FreeRTOS scheduler — never returns */
    osKernelStart();

    /* Should never reach here */
    while (1) {}
}

/* ============================================================
 * Task 1: Wireless RX — HIGH priority
 * Receives packets from both RF bands simultaneously
 * ============================================================ */
void Task_WirelessRX(void *argument)
{
    MotorPacket_t pktA, pktB;
    uint8_t bufA[sizeof(MotorPacket_t)];
    uint8_t bufB[sizeof(MotorPacket_t)];
    uint8_t lenA, lenB;

    for (;;)
    {
        /* Try to receive from Stream A (2.4 GHz — primary) */
        if (radio_receive(BAND_2G4, bufA, &lenA) == HAL_OK)
        {
            memcpy(&pktA, bufA, sizeof(MotorPacket_t));

            /* Validate checksum */
            if (calc_checksum(&pktA) == pktA.checksum)
            {
                lastSeqA  = pktA.seq;
                lastTimeA = HAL_GetTick();

                /* Only use if TX-A is active band */
                osMutexAcquire(activeBandMutexHandle, osWaitForever);
                if (activeBand == BAND_2G4)
                {
                    osMessageQueuePut(motorCmdQueueHandle, &pktA, 0, 0);
                }
                osMutexRelease(activeBandMutexHandle);
            }
        }

        /* Try to receive from Stream B (868 MHz — backup) */
        if (radio_receive(BAND_868, bufB, &lenB) == HAL_OK)
        {
            memcpy(&pktB, bufB, sizeof(MotorPacket_t));

            /* Validate checksum */
            if (calc_checksum(&pktB) == pktB.checksum)
            {
                lastSeqB  = pktB.seq;
                lastTimeB = HAL_GetTick();

                /* Only use if TX-B is active band (after failover) */
                osMutexAcquire(activeBandMutexHandle, osWaitForever);
                if (activeBand == BAND_868)
                {
                    /* Deduplicate: ignore if same seq as last A packet */
                    if (pktB.seq != lastSeqA)
                    {
                        osMessageQueuePut(motorCmdQueueHandle, &pktB, 0, 0);
                    }
                }
                osMutexRelease(activeBandMutexHandle);
            }
        }

        osDelay(5); // 5ms polling interval
    }
}

/* ============================================================
 * Task 2: Motor Control — HIGH priority
 * Reads commands from queue and drives PWM
 * ============================================================ */
void Task_MotorControl(void *argument)
{
    MotorPacket_t cmd;

    for (;;)
    {
        /* Block until a command arrives in queue */
        if (osMessageQueueGet(motorCmdQueueHandle, &cmd, NULL, 100) == osOK)
        {
            switch (cmd.cmd)
            {
                case MOTOR_FWD:
                    motor_set_direction(FORWARD);
                    motor_set_speed(cmd.seq); // seq reused as speed 0-100%
                    break;

                case MOTOR_REV:
                    motor_set_direction(REVERSE);
                    motor_set_speed(cmd.seq);
                    break;

                case MOTOR_STOP:
                    motor_stop();
                    log_uart("[MOTOR] Stop command received\r\n");
                    break;

                default:
                    break;
            }
        }
    }
}

/* ============================================================
 * Task 3: Redundancy Manager — NORMAL priority
 * Monitors both streams and switches if TX-A fails
 * ============================================================ */
void Task_Redundancy(void *argument)
{
    uint32_t flags;

    for (;;)
    {
        /* Wait for TX-A failure event from Health Monitor */
        flags = osEventFlagsWait(
            systemEventHandle,
            EVT_TXA_FAIL,
            osFlagsWaitAny,
            osWaitForever
        );

        if (flags & EVT_TXA_FAIL)
        {
            log_uart("[REDUND] TX-A failure detected!\r\n");
            log_uart("[REDUND] Switching to TX-B (868 MHz)...\r\n");

            /* Switch active band to TX-B */
            osMutexAcquire(activeBandMutexHandle, osWaitForever);
            activeBand = BAND_868;
            osMutexRelease(activeBandMutexHandle);

            /* Validate TX-B stream is alive */
            uint32_t now = HAL_GetTick();
            if ((now - lastTimeB) < STREAM_TIMEOUT_MS)
            {
                log_uart("[REDUND] TX-B validated — stream OK\r\n");
                log_uart("[REDUND] Motor continues — NO interruption\r\n");
                osEventFlagsSet(systemEventHandle, EVT_SWITCH_DONE);
            }
            else
            {
                log_uart("[REDUND] WARNING: TX-B stream not available!\r\n");
            }
        }

        osDelay(10);
    }
}

/* ============================================================
 * Task 4: Health Monitor — LOW priority
 * Watches stream timeouts and fires alerts
 * ============================================================ */
void Task_HealthMonitor(void *argument)
{
    char logBuf[80];

    for (;;)
    {
        uint32_t now = HAL_GetTick();

        /* Check Stream A timeout */
        osMutexAcquire(activeBandMutexHandle, osWaitForever);
        RadioBand current = activeBand;
        osMutexRelease(activeBandMutexHandle);

        if (current == BAND_2G4)
        {
            if ((now - lastTimeA) > STREAM_TIMEOUT_MS)
            {
                snprintf(logBuf, sizeof(logBuf),
                    "[HEALTH] Stream A timeout (%lu ms) — firing TX-A fail event\r\n",
                    (now - lastTimeA));
                log_uart(logBuf);

                /* Fire TX-A failure event to Redundancy task */
                osEventFlagsSet(systemEventHandle, EVT_TXA_FAIL);
            }
        }

        /* Log RSSI every 1 second */
        static uint32_t lastLog = 0;
        if ((now - lastLog) > 1000)
        {
            snprintf(logBuf, sizeof(logBuf),
                "[HEALTH] Active band: %s | SeqA=%d SeqB=%d\r\n",
                (current == BAND_2G4) ? "2.4GHz" : "868MHz",
                lastSeqA, lastSeqB);
            log_uart(logBuf);
            lastLog = now;
        }

        osDelay(10); // check every 10ms
    }
}

/* ============================================================
 * Helpers
 * ============================================================ */
static void log_uart(const char *msg)
{
    HAL_UART_Transmit(&huart1, (uint8_t*)msg, strlen(msg), HAL_MAX_DELAY);
}

static uint8_t calc_checksum(MotorPacket_t *pkt)
{
    return pkt->cmd ^ pkt->seq ^
           (uint8_t)(pkt->timestamp & 0xFF) ^
           (uint8_t)((pkt->timestamp >> 8) & 0xFF);
}

/* ============================================================
 * Error handler
 * ============================================================ */
void Error_Handler(void)
{
    __disable_irq();
    log_uart("[ERROR] Fatal error — system halted\r\n");
    while (1) {}
}
